# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.60</version>
#    <timestamp>2026-05-13T14:01:48.856Z</timestamp>
#    <hash>2c9892f06100ba70</hash>
# </meta>

fabric:
  - "/^fabric$/m"
forge:
  - "/^forge$/m"
