# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.93</version>
#    <timestamp>2026-06-17T16:44:41.300Z</timestamp>
#    <hash>a8ae56f8fbeece83</hash>
# </meta>

fabric:
  - "/^fabric$/m"
forge:
  - "/^forge$/m"
neoforge:
  - "/^neoforge$/m"

1.21.x:
  - "/^1.21$/m"
1.20.x:
  - "/^1.20$/m"
