# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
fabric_loader_version=0.17.2
fabric_api_version=0.92.6+1.20.1

# Mod Properties
mod_version=0.0.0-dev
mod_name=Dye Depot
mod_id=dye_depot
mod_description=Enhances your Minecraft experience with 16 vibrant new dyes and various other tweaks
release_type=release
java_version=21

# Publishing
maven_group=com.ninni.dye_depot
repository=pssbletrngle/dye_depot
modrinth_project_id=dl88rsIq
curseforge_project_id=988504
