# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Neoforge Properties
minecraft_version=26.1.2
neoforge_version=26.1.2.43-beta

# Mod Properties
mod_version=0.0.0-dev
mod_name=Dye Depot
mod_id=dye_depot
mod_description=Enhances your Minecraft experience with 16 vibrant new dyes and various other tweaks
release_type=beta

# TODO move to gradle helper
java_version=25

# Publishing
maven_group=com.ninni.dye_depot
repository=n1nn1/dye_depot
modrinth_project_id=dl88rsIq
curseforge_project_id=988504
