modLoader = "javafml"
loaderVersion = "[47,)"
license = "CC0-1.0"
issueTrackerURL = "https://github.com/${repository}/issues/"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_id}/icon.png"
authors = "Yapetto, Ninni"
description = '''Enhances your Minecraft experience with 16 vibrant new dyes and various other tweaks'''
updateJSONURL = "https://api.modrinth.com/updates/dye-depot/forge_updates.json"
itemIcon = "dye_depot:teal_dye"
configBackground = "dye_depot:textures/block/teal_glazed_terracotta.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "supplementaries"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "suppsquared"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "BOTH"