[versions]
jei = "19.27.0.340"
porting-lib = "3.1.0-1+1.21.1"

[libraries]
jei-common-api = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jei" }
jei = { group = "mezz.jei", name = "jei-1.21.1-fabric", version.ref = "jei" }

porting-lib-models = { group = "io.github.fabricators_of_create.Porting-Lib", name = "models", version.ref = "porting-lib" }
