name: Bug Report
description: File a bug report
labels: ["bug"]

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: version-version
    attributes:
      label: Mod Version
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Minecraft Version
      multiple: false
      options:
        - "1.21"
        - "1.20"
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: log output
      description: Please copy and paste your log output to https://mclo.gs/ or a similar site and paste the link here.