# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.104</version>
#    <timestamp>2026-06-29T14:17:47.575Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
