# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>0.0.0-dev</version>
#    <timestamp>2026-05-08T10:03:11.402Z</timestamp>
#    <hash>50bdd3d142fbd99f</hash>
# </meta>

blank_issues_enabled: false
