name = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "279da118002be1e2bb8f01abeccc497eeb6444a6f86c37f73e999bc0fea3d943"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
