package com.ninni.dye_depot.registry;

import com.ninni.dye_depot.DyeDepot;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Block;

import java.util.Map;
import java.util.function.Function;

public class DDItems {

    public static final Item MAROON_DYE = register("maroon_dye", new DyeItem(DDDyes.MAROON.get(), new Item.Properties()));
    public static final Item ROSE_DYE = register("rose_dye", new DyeItem(DDDyes.ROSE.get(), new Item.Properties()));
    public static final Item CORAL_DYE = register("coral_dye", new DyeItem(DDDyes.CORAL.get(), new Item.Properties()));
    public static final Item INDIGO_DYE = register("indigo_dye", new DyeItem(DDDyes.INDIGO.get(), new Item.Properties()));
    public static final Item NAVY_DYE = register("navy_dye", new DyeItem(DDDyes.NAVY.get(), new Item.Properties()));
    public static final Item SLATE_DYE = register("slate_dye", new DyeItem(DDDyes.SLATE.get(), new Item.Properties()));
    public static final Item OLIVE_DYE = register("olive_dye", new DyeItem(DDDyes.OLIVE.get(), new Item.Properties()));
    public static final Item AMBER_DYE = register("amber_dye", new DyeItem(DDDyes.AMBER.get(), new Item.Properties()));
    public static final Item BEIGE_DYE = register("beige_dye", new DyeItem(DDDyes.BEIGE.get(), new Item.Properties()));
    public static final Item TEAL_DYE = register("teal_dye", new DyeItem(DDDyes.TEAL.get(), new Item.Properties()));
    public static final Item MINT_DYE = register("mint_dye", new DyeItem(DDDyes.MINT.get(), new Item.Properties()));
    public static final Item AQUA_DYE = register("aqua_dye", new DyeItem(DDDyes.AQUA.get(), new Item.Properties()));
    public static final Item VERDANT_DYE = register("verdant_dye", new DyeItem(DDDyes.VERDANT.get(), new Item.Properties()));
    public static final Item FOREST_DYE = register("forest_dye", new DyeItem(DDDyes.FOREST.get(), new Item.Properties()));
    public static final Item GINGER_DYE = register("ginger_dye", new DyeItem(DDDyes.GINGER.get(), new Item.Properties()));
    public static final Item TAN_DYE = register("tan_dye", new DyeItem(DDDyes.TAN.get(), new Item.Properties()));

    public static final Item MAROON_WOOL = register("maroon_wool", new BlockItem(DDBlocks.MAROON_WOOL, new Item.Properties()));
    public static final Item ROSE_WOOL = register("rose_wool", new BlockItem(DDBlocks.ROSE_WOOL, new Item.Properties()));
    public static final Item CORAL_WOOL = register("coral_wool", new BlockItem(DDBlocks.CORAL_WOOL, new Item.Properties()));
    public static final Item INDIGO_WOOL = register("indigo_wool", new BlockItem(DDBlocks.INDIGO_WOOL, new Item.Properties()));
    public static final Item NAVY_WOOL = register("navy_wool", new BlockItem(DDBlocks.NAVY_WOOL, new Item.Properties()));
    public static final Item SLATE_WOOL = register("slate_wool", new BlockItem(DDBlocks.SLATE_WOOL, new Item.Properties()));
    public static final Item OLIVE_WOOL = register("olive_wool", new BlockItem(DDBlocks.OLIVE_WOOL, new Item.Properties()));
    public static final Item AMBER_WOOL = register("amber_wool", new BlockItem(DDBlocks.AMBER_WOOL, new Item.Properties()));
    public static final Item BEIGE_WOOL = register("beige_wool", new BlockItem(DDBlocks.BEIGE_WOOL, new Item.Properties()));
    public static final Item TEAL_WOOL = register("teal_wool", new BlockItem(DDBlocks.TEAL_WOOL, new Item.Properties()));
    public static final Item MINT_WOOL = register("mint_wool", new BlockItem(DDBlocks.MINT_WOOL, new Item.Properties()));
    public static final Item AQUA_WOOL = register("aqua_wool", new BlockItem(DDBlocks.AQUA_WOOL, new Item.Properties()));
    public static final Item VERDANT_WOOL = register("verdant_wool", new BlockItem(DDBlocks.VERDANT_WOOL, new Item.Properties()));
    public static final Item FOREST_WOOL = register("forest_wool", new BlockItem(DDBlocks.FOREST_WOOL, new Item.Properties()));
    public static final Item GINGER_WOOL = register("ginger_wool", new BlockItem(DDBlocks.GINGER_WOOL, new Item.Properties()));
    public static final Item TAN_WOOL = register("tan_wool", new BlockItem(DDBlocks.TAN_WOOL, new Item.Properties()));

    public static final Item MAROON_CARPET = register("maroon_carpet", new BlockItem(DDBlocks.MAROON_CARPET, new Item.Properties()));
    public static final Item ROSE_CARPET = register("rose_carpet", new BlockItem(DDBlocks.ROSE_CARPET, new Item.Properties()));
    public static final Item CORAL_CARPET = register("coral_carpet", new BlockItem(DDBlocks.CORAL_CARPET, new Item.Properties()));
    public static final Item INDIGO_CARPET = register("indigo_carpet", new BlockItem(DDBlocks.INDIGO_CARPET, new Item.Properties()));
    public static final Item NAVY_CARPET = register("navy_carpet", new BlockItem(DDBlocks.NAVY_CARPET, new Item.Properties()));
    public static final Item SLATE_CARPET = register("slate_carpet", new BlockItem(DDBlocks.SLATE_CARPET, new Item.Properties()));
    public static final Item OLIVE_CARPET = register("olive_carpet", new BlockItem(DDBlocks.OLIVE_CARPET, new Item.Properties()));
    public static final Item AMBER_CARPET = register("amber_carpet", new BlockItem(DDBlocks.AMBER_CARPET, new Item.Properties()));
    public static final Item BEIGE_CARPET = register("beige_carpet", new BlockItem(DDBlocks.BEIGE_CARPET, new Item.Properties()));
    public static final Item TEAL_CARPET = register("teal_carpet", new BlockItem(DDBlocks.TEAL_CARPET, new Item.Properties()));
    public static final Item MINT_CARPET = register("mint_carpet", new BlockItem(DDBlocks.MINT_CARPET, new Item.Properties()));
    public static final Item AQUA_CARPET = register("aqua_carpet", new BlockItem(DDBlocks.AQUA_CARPET, new Item.Properties()));
    public static final Item VERDANT_CARPET = register("verdant_carpet", new BlockItem(DDBlocks.VERDANT_CARPET, new Item.Properties()));
    public static final Item FOREST_CARPET = register("forest_carpet", new BlockItem(DDBlocks.FOREST_CARPET, new Item.Properties()));
    public static final Item GINGER_CARPET = register("ginger_carpet", new BlockItem(DDBlocks.GINGER_CARPET, new Item.Properties()));
    public static final Item TAN_CARPET = register("tan_carpet", new BlockItem(DDBlocks.TAN_CARPET, new Item.Properties()));

    public static final Item MAROON_TERRACOTTA = register("maroon_terracotta", new BlockItem(DDBlocks.MAROON_TERRACOTTA, new Item.Properties()));
    public static final Item ROSE_TERRACOTTA = register("rose_terracotta", new BlockItem(DDBlocks.ROSE_TERRACOTTA, new Item.Properties()));
    public static final Item CORAL_TERRACOTTA = register("coral_terracotta", new BlockItem(DDBlocks.CORAL_TERRACOTTA, new Item.Properties()));
    public static final Item INDIGO_TERRACOTTA = register("indigo_terracotta", new BlockItem(DDBlocks.INDIGO_TERRACOTTA, new Item.Properties()));
    public static final Item NAVY_TERRACOTTA = register("navy_terracotta", new BlockItem(DDBlocks.NAVY_TERRACOTTA, new Item.Properties()));
    public static final Item SLATE_TERRACOTTA = register("slate_terracotta", new BlockItem(DDBlocks.SLATE_TERRACOTTA, new Item.Properties()));
    public static final Item OLIVE_TERRACOTTA = register("olive_terracotta", new BlockItem(DDBlocks.OLIVE_TERRACOTTA, new Item.Properties()));
    public static final Item AMBER_TERRACOTTA = register("amber_terracotta", new BlockItem(DDBlocks.AMBER_TERRACOTTA, new Item.Properties()));
    public static final Item BEIGE_TERRACOTTA = register("beige_terracotta", new BlockItem(DDBlocks.BEIGE_TERRACOTTA, new Item.Properties()));
    public static final Item TEAL_TERRACOTTA = register("teal_terracotta", new BlockItem(DDBlocks.TEAL_TERRACOTTA, new Item.Properties()));
    public static final Item MINT_TERRACOTTA = register("mint_terracotta", new BlockItem(DDBlocks.MINT_TERRACOTTA, new Item.Properties()));
    public static final Item AQUA_TERRACOTTA = register("aqua_terracotta", new BlockItem(DDBlocks.AQUA_TERRACOTTA, new Item.Properties()));
    public static final Item VERDANT_TERRACOTTA = register("verdant_terracotta", new BlockItem(DDBlocks.VERDANT_TERRACOTTA, new Item.Properties()));
    public static final Item FOREST_TERRACOTTA = register("forest_terracotta", new BlockItem(DDBlocks.FOREST_TERRACOTTA, new Item.Properties()));
    public static final Item GINGER_TERRACOTTA = register("ginger_terracotta", new BlockItem(DDBlocks.GINGER_TERRACOTTA, new Item.Properties()));
    public static final Item TAN_TERRACOTTA = register("tan_terracotta", new BlockItem(DDBlocks.TAN_TERRACOTTA, new Item.Properties()));

    public static final Item MAROON_CONCRETE = register("maroon_concrete", new BlockItem(DDBlocks.MAROON_CONCRETE, new Item.Properties()));
    public static final Item ROSE_CONCRETE = register("rose_concrete", new BlockItem(DDBlocks.ROSE_CONCRETE, new Item.Properties()));
    public static final Item CORAL_CONCRETE = register("coral_concrete", new BlockItem(DDBlocks.CORAL_CONCRETE, new Item.Properties()));
    public static final Item INDIGO_CONCRETE = register("indigo_concrete", new BlockItem(DDBlocks.INDIGO_CONCRETE, new Item.Properties()));
    public static final Item NAVY_CONCRETE = register("navy_concrete", new BlockItem(DDBlocks.NAVY_CONCRETE, new Item.Properties()));
    public static final Item SLATE_CONCRETE = register("slate_concrete", new BlockItem(DDBlocks.SLATE_CONCRETE, new Item.Properties()));
    public static final Item OLIVE_CONCRETE = register("olive_concrete", new BlockItem(DDBlocks.OLIVE_CONCRETE, new Item.Properties()));
    public static final Item AMBER_CONCRETE = register("amber_concrete", new BlockItem(DDBlocks.AMBER_CONCRETE, new Item.Properties()));
    public static final Item BEIGE_CONCRETE = register("beige_concrete", new BlockItem(DDBlocks.BEIGE_CONCRETE, new Item.Properties()));
    public static final Item TEAL_CONCRETE = register("teal_concrete", new BlockItem(DDBlocks.TEAL_CONCRETE, new Item.Properties()));
    public static final Item MINT_CONCRETE = register("mint_concrete", new BlockItem(DDBlocks.MINT_CONCRETE, new Item.Properties()));
    public static final Item AQUA_CONCRETE = register("aqua_concrete", new BlockItem(DDBlocks.AQUA_CONCRETE, new Item.Properties()));
    public static final Item VERDANT_CONCRETE = register("verdant_concrete", new BlockItem(DDBlocks.VERDANT_CONCRETE, new Item.Properties()));
    public static final Item FOREST_CONCRETE = register("forest_concrete", new BlockItem(DDBlocks.FOREST_CONCRETE, new Item.Properties()));
    public static final Item GINGER_CONCRETE = register("ginger_concrete", new BlockItem(DDBlocks.GINGER_CONCRETE, new Item.Properties()));
    public static final Item TAN_CONCRETE = register("tan_concrete", new BlockItem(DDBlocks.TAN_CONCRETE, new Item.Properties()));

    public static final Item MAROON_CONCRETE_POWDER = register("maroon_concrete_powder", new BlockItem(DDBlocks.MAROON_CONCRETE_POWDER, new Item.Properties()));
    public static final Item ROSE_CONCRETE_POWDER = register("rose_concrete_powder", new BlockItem(DDBlocks.ROSE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item CORAL_CONCRETE_POWDER = register("coral_concrete_powder", new BlockItem(DDBlocks.CORAL_CONCRETE_POWDER, new Item.Properties()));
    public static final Item INDIGO_CONCRETE_POWDER = register("indigo_concrete_powder", new BlockItem(DDBlocks.INDIGO_CONCRETE_POWDER, new Item.Properties()));
    public static final Item NAVY_CONCRETE_POWDER = register("navy_concrete_powder", new BlockItem(DDBlocks.NAVY_CONCRETE_POWDER, new Item.Properties()));
    public static final Item SLATE_CONCRETE_POWDER = register("slate_concrete_powder", new BlockItem(DDBlocks.SLATE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item OLIVE_CONCRETE_POWDER = register("olive_concrete_powder", new BlockItem(DDBlocks.OLIVE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item AMBER_CONCRETE_POWDER = register("amber_concrete_powder", new BlockItem(DDBlocks.AMBER_CONCRETE_POWDER, new Item.Properties()));
    public static final Item BEIGE_CONCRETE_POWDER = register("beige_concrete_powder", new BlockItem(DDBlocks.BEIGE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item TEAL_CONCRETE_POWDER = register("teal_concrete_powder", new BlockItem(DDBlocks.TEAL_CONCRETE_POWDER, new Item.Properties()));
    public static final Item MINT_CONCRETE_POWDER = register("mint_concrete_powder", new BlockItem(DDBlocks.MINT_CONCRETE_POWDER, new Item.Properties()));
    public static final Item AQUA_CONCRETE_POWDER = register("aqua_concrete_powder", new BlockItem(DDBlocks.AQUA_CONCRETE_POWDER, new Item.Properties()));
    public static final Item VERDANT_CONCRETE_POWDER = register("verdant_concrete_powder", new BlockItem(DDBlocks.VERDANT_CONCRETE_POWDER, new Item.Properties()));
    public static final Item FOREST_CONCRETE_POWDER = register("forest_concrete_powder", new BlockItem(DDBlocks.FOREST_CONCRETE_POWDER, new Item.Properties()));
    public static final Item GINGER_CONCRETE_POWDER = register("ginger_concrete_powder", new BlockItem(DDBlocks.GINGER_CONCRETE_POWDER, new Item.Properties()));
    public static final Item TAN_CONCRETE_POWDER = register("tan_concrete_powder", new BlockItem(DDBlocks.TAN_CONCRETE_POWDER, new Item.Properties()));

    public static final Item MAROON_GLAZED_TERRACOTTA = register("maroon_glazed_terracotta", new BlockItem(DDBlocks.MAROON_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item ROSE_GLAZED_TERRACOTTA = register("rose_glazed_terracotta", new BlockItem(DDBlocks.ROSE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item CORAL_GLAZED_TERRACOTTA = register("coral_glazed_terracotta", new BlockItem(DDBlocks.CORAL_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item INDIGO_GLAZED_TERRACOTTA = register("indigo_glazed_terracotta", new BlockItem(DDBlocks.INDIGO_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item NAVY_GLAZED_TERRACOTTA = register("navy_glazed_terracotta", new BlockItem(DDBlocks.NAVY_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item SLATE_GLAZED_TERRACOTTA = register("slate_glazed_terracotta", new BlockItem(DDBlocks.SLATE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item OLIVE_GLAZED_TERRACOTTA = register("olive_glazed_terracotta", new BlockItem(DDBlocks.OLIVE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item AMBER_GLAZED_TERRACOTTA = register("amber_glazed_terracotta", new BlockItem(DDBlocks.AMBER_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item BEIGE_GLAZED_TERRACOTTA = register("beige_glazed_terracotta", new BlockItem(DDBlocks.BEIGE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item TEAL_GLAZED_TERRACOTTA = register("teal_glazed_terracotta", new BlockItem(DDBlocks.TEAL_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item MINT_GLAZED_TERRACOTTA = register("mint_glazed_terracotta", new BlockItem(DDBlocks.MINT_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item AQUA_GLAZED_TERRACOTTA = register("aqua_glazed_terracotta", new BlockItem(DDBlocks.AQUA_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item VERDANT_GLAZED_TERRACOTTA = register("verdant_glazed_terracotta", new BlockItem(DDBlocks.VERDANT_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item FOREST_GLAZED_TERRACOTTA = register("forest_glazed_terracotta", new BlockItem(DDBlocks.FOREST_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item GINGER_GLAZED_TERRACOTTA = register("ginger_glazed_terracotta", new BlockItem(DDBlocks.GINGER_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item TAN_GLAZED_TERRACOTTA = register("tan_glazed_terracotta", new BlockItem(DDBlocks.TAN_GLAZED_TERRACOTTA, new Item.Properties()));

    public static final Item MAROON_STAINED_GLASS = register("maroon_stained_glass", new BlockItem(DDBlocks.MAROON_STAINED_GLASS, new Item.Properties()));
    public static final Item ROSE_STAINED_GLASS = register("rose_stained_glass", new BlockItem(DDBlocks.ROSE_STAINED_GLASS, new Item.Properties()));
    public static final Item CORAL_STAINED_GLASS = register("coral_stained_glass", new BlockItem(DDBlocks.CORAL_STAINED_GLASS, new Item.Properties()));
    public static final Item INDIGO_STAINED_GLASS = register("indigo_stained_glass", new BlockItem(DDBlocks.INDIGO_STAINED_GLASS, new Item.Properties()));
    public static final Item NAVY_STAINED_GLASS = register("navy_stained_glass", new BlockItem(DDBlocks.NAVY_STAINED_GLASS, new Item.Properties()));
    public static final Item SLATE_STAINED_GLASS = register("slate_stained_glass", new BlockItem(DDBlocks.SLATE_STAINED_GLASS, new Item.Properties()));
    public static final Item OLIVE_STAINED_GLASS = register("olive_stained_glass", new BlockItem(DDBlocks.OLIVE_STAINED_GLASS, new Item.Properties()));
    public static final Item AMBER_STAINED_GLASS = register("amber_stained_glass", new BlockItem(DDBlocks.AMBER_STAINED_GLASS, new Item.Properties()));
    public static final Item BEIGE_STAINED_GLASS = register("beige_stained_glass", new BlockItem(DDBlocks.BEIGE_STAINED_GLASS, new Item.Properties()));
    public static final Item TEAL_STAINED_GLASS = register("teal_stained_glass", new BlockItem(DDBlocks.TEAL_STAINED_GLASS, new Item.Properties()));
    public static final Item MINT_STAINED_GLASS = register("mint_stained_glass", new BlockItem(DDBlocks.MINT_STAINED_GLASS, new Item.Properties()));
    public static final Item AQUA_STAINED_GLASS = register("aqua_stained_glass", new BlockItem(DDBlocks.AQUA_STAINED_GLASS, new Item.Properties()));
    public static final Item VERDANT_STAINED_GLASS = register("verdant_stained_glass", new BlockItem(DDBlocks.VERDANT_STAINED_GLASS, new Item.Properties()));
    public static final Item FOREST_STAINED_GLASS = register("forest_stained_glass", new BlockItem(DDBlocks.FOREST_STAINED_GLASS, new Item.Properties()));
    public static final Item GINGER_STAINED_GLASS = register("ginger_stained_glass", new BlockItem(DDBlocks.GINGER_STAINED_GLASS, new Item.Properties()));
    public static final Item TAN_STAINED_GLASS = register("tan_stained_glass", new BlockItem(DDBlocks.TAN_STAINED_GLASS, new Item.Properties()));

    public static final Item MAROON_STAINED_GLASS_PANE = register("maroon_stained_glass_pane", new BlockItem(DDBlocks.MAROON_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item ROSE_STAINED_GLASS_PANE = register("rose_stained_glass_pane", new BlockItem(DDBlocks.ROSE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item CORAL_STAINED_GLASS_PANE = register("coral_stained_glass_pane", new BlockItem(DDBlocks.CORAL_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item INDIGO_STAINED_GLASS_PANE = register("indigo_stained_glass_pane", new BlockItem(DDBlocks.INDIGO_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item NAVY_STAINED_GLASS_PANE = register("navy_stained_glass_pane", new BlockItem(DDBlocks.NAVY_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item SLATE_STAINED_GLASS_PANE = register("slate_stained_glass_pane", new BlockItem(DDBlocks.SLATE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item OLIVE_STAINED_GLASS_PANE = register("olive_stained_glass_pane", new BlockItem(DDBlocks.OLIVE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item AMBER_STAINED_GLASS_PANE = register("amber_stained_glass_pane", new BlockItem(DDBlocks.AMBER_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item BEIGE_STAINED_GLASS_PANE = register("beige_stained_glass_pane", new BlockItem(DDBlocks.BEIGE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item TEAL_STAINED_GLASS_PANE = register("teal_stained_glass_pane", new BlockItem(DDBlocks.TEAL_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item MINT_STAINED_GLASS_PANE = register("mint_stained_glass_pane", new BlockItem(DDBlocks.MINT_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item AQUA_STAINED_GLASS_PANE = register("aqua_stained_glass_pane", new BlockItem(DDBlocks.AQUA_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item VERDANT_STAINED_GLASS_PANE = register("verdant_stained_glass_pane", new BlockItem(DDBlocks.VERDANT_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item FOREST_STAINED_GLASS_PANE = register("forest_stained_glass_pane", new BlockItem(DDBlocks.FOREST_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item GINGER_STAINED_GLASS_PANE = register("ginger_stained_glass_pane", new BlockItem(DDBlocks.GINGER_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item TAN_STAINED_GLASS_PANE = register("tan_stained_glass_pane", new BlockItem(DDBlocks.TAN_STAINED_GLASS_PANE, new Item.Properties()));

    public static final DyedHolders<Item> SHULKER_BOXES = DyedHolders.create(dye ->
        register(dye + "_shulker_box", new BlockItem(DDBlocks.SHULKER_BOXES.getOrThrow(dye), new Item.Properties().stacksTo(1)))
    );

    public static final Item MAROON_CANDLE = register("maroon_candle", new BlockItem(DDBlocks.MAROON_CANDLE, new Item.Properties()));
    public static final Item ROSE_CANDLE = register("rose_candle", new BlockItem(DDBlocks.ROSE_CANDLE, new Item.Properties()));
    public static final Item CORAL_CANDLE = register("coral_candle", new BlockItem(DDBlocks.CORAL_CANDLE, new Item.Properties()));
    public static final Item INDIGO_CANDLE = register("indigo_candle", new BlockItem(DDBlocks.INDIGO_CANDLE, new Item.Properties()));
    public static final Item NAVY_CANDLE = register("navy_candle", new BlockItem(DDBlocks.NAVY_CANDLE, new Item.Properties()));
    public static final Item SLATE_CANDLE = register("slate_candle", new BlockItem(DDBlocks.SLATE_CANDLE, new Item.Properties()));
    public static final Item OLIVE_CANDLE = register("olive_candle", new BlockItem(DDBlocks.OLIVE_CANDLE, new Item.Properties()));
    public static final Item AMBER_CANDLE = register("amber_candle", new BlockItem(DDBlocks.AMBER_CANDLE, new Item.Properties()));
    public static final Item BEIGE_CANDLE = register("beige_candle", new BlockItem(DDBlocks.BEIGE_CANDLE, new Item.Properties()));
    public static final Item TEAL_CANDLE = register("teal_candle", new BlockItem(DDBlocks.TEAL_CANDLE, new Item.Properties()));
    public static final Item MINT_CANDLE = register("mint_candle", new BlockItem(DDBlocks.MINT_CANDLE, new Item.Properties()));
    public static final Item AQUA_CANDLE = register("aqua_candle", new BlockItem(DDBlocks.AQUA_CANDLE, new Item.Properties()));
    public static final Item VERDANT_CANDLE = register("verdant_candle", new BlockItem(DDBlocks.VERDANT_CANDLE, new Item.Properties()));
    public static final Item FOREST_CANDLE = register("forest_candle", new BlockItem(DDBlocks.FOREST_CANDLE, new Item.Properties()));
    public static final Item GINGER_CANDLE = register("ginger_candle", new BlockItem(DDBlocks.GINGER_CANDLE, new Item.Properties()));
    public static final Item TAN_CANDLE = register("tan_candle", new BlockItem(DDBlocks.TAN_CANDLE, new Item.Properties()));

    public static final Item MAROON_BANNER = register("maroon_banner", new BannerItem(DDBlocks.MAROON_BANNER,DDBlocks.MAROON_WALL_BANNER, new Item.Properties()));
    public static final Item ROSE_BANNER = register("rose_banner", new BannerItem(DDBlocks.ROSE_BANNER,DDBlocks.ROSE_WALL_BANNER, new Item.Properties()));
    public static final Item CORAL_BANNER = register("coral_banner", new BannerItem(DDBlocks.CORAL_BANNER,DDBlocks.CORAL_WALL_BANNER, new Item.Properties()));
    public static final Item INDIGO_BANNER = register("indigo_banner", new BannerItem(DDBlocks.INDIGO_BANNER,DDBlocks.INDIGO_WALL_BANNER, new Item.Properties()));
    public static final Item NAVY_BANNER = register("navy_banner", new BannerItem(DDBlocks.NAVY_BANNER,DDBlocks.NAVY_WALL_BANNER, new Item.Properties()));
    public static final Item SLATE_BANNER = register("slate_banner", new BannerItem(DDBlocks.SLATE_BANNER,DDBlocks.SLATE_WALL_BANNER, new Item.Properties()));
    public static final Item OLIVE_BANNER = register("olive_banner", new BannerItem(DDBlocks.OLIVE_BANNER,DDBlocks.OLIVE_WALL_BANNER, new Item.Properties()));
    public static final Item AMBER_BANNER = register("amber_banner", new BannerItem(DDBlocks.AMBER_BANNER,DDBlocks.AMBER_WALL_BANNER, new Item.Properties()));
    public static final Item BEIGE_BANNER = register("beige_banner", new BannerItem(DDBlocks.BEIGE_BANNER,DDBlocks.BEIGE_WALL_BANNER, new Item.Properties()));
    public static final Item TEAL_BANNER = register("teal_banner", new BannerItem(DDBlocks.TEAL_BANNER,DDBlocks.TEAL_WALL_BANNER, new Item.Properties()));
    public static final Item MINT_BANNER = register("mint_banner", new BannerItem(DDBlocks.MINT_BANNER,DDBlocks.MINT_WALL_BANNER, new Item.Properties()));
    public static final Item AQUA_BANNER = register("aqua_banner", new BannerItem(DDBlocks.AQUA_BANNER,DDBlocks.AQUA_WALL_BANNER, new Item.Properties()));
    public static final Item VERDANT_BANNER = register("verdant_banner", new BannerItem(DDBlocks.VERDANT_BANNER,DDBlocks.VERDANT_WALL_BANNER, new Item.Properties()));
    public static final Item FOREST_BANNER = register("forest_banner", new BannerItem(DDBlocks.FOREST_BANNER,DDBlocks.FOREST_WALL_BANNER, new Item.Properties()));
    public static final Item GINGER_BANNER = register("ginger_banner", new BannerItem(DDBlocks.GINGER_BANNER,DDBlocks.GINGER_WALL_BANNER, new Item.Properties()));
    public static final Item TAN_BANNER = register("tan_banner", new BannerItem(DDBlocks.TAN_BANNER,DDBlocks.TAN_WALL_BANNER, new Item.Properties()));

    public static final Item MAROON_BED = register("maroon_bed", new BedItem(DDBlocks.MAROON_BED, new Item.Properties().stacksTo(1)));
    public static final Item ROSE_BED = register("rose_bed", new BedItem(DDBlocks.ROSE_BED, new Item.Properties().stacksTo(1)));
    public static final Item CORAL_BED = register("coral_bed", new BedItem(DDBlocks.CORAL_BED, new Item.Properties().stacksTo(1)));
    public static final Item INDIGO_BED = register("indigo_bed", new BedItem(DDBlocks.INDIGO_BED, new Item.Properties().stacksTo(1)));
    public static final Item NAVY_BED = register("navy_bed", new BedItem(DDBlocks.NAVY_BED, new Item.Properties().stacksTo(1)));
    public static final Item SLATE_BED = register("slate_bed", new BedItem(DDBlocks.SLATE_BED, new Item.Properties().stacksTo(1)));
    public static final Item OLIVE_BED = register("olive_bed", new BedItem(DDBlocks.OLIVE_BED, new Item.Properties().stacksTo(1)));
    public static final Item AMBER_BED = register("amber_bed", new BedItem(DDBlocks.AMBER_BED, new Item.Properties().stacksTo(1)));
    public static final Item BEIGE_BED = register("beige_bed", new BedItem(DDBlocks.BEIGE_BED, new Item.Properties().stacksTo(1)));
    public static final Item TEAL_BED = register("teal_bed", new BedItem(DDBlocks.TEAL_BED, new Item.Properties().stacksTo(1)));
    public static final Item MINT_BED = register("mint_bed", new BedItem(DDBlocks.MINT_BED, new Item.Properties().stacksTo(1)));
    public static final Item AQUA_BED = register("aqua_bed", new BedItem(DDBlocks.AQUA_BED, new Item.Properties().stacksTo(1)));
    public static final Item VERDANT_BED = register("verdant_bed", new BedItem(DDBlocks.VERDANT_BED, new Item.Properties().stacksTo(1)));
    public static final Item FOREST_BED = register("forest_bed", new BedItem(DDBlocks.FOREST_BED, new Item.Properties().stacksTo(1)));
    public static final Item GINGER_BED = register("ginger_bed", new BedItem(DDBlocks.GINGER_BED, new Item.Properties().stacksTo(1)));
    public static final Item TAN_BED = register("tan_bed", new BedItem(DDBlocks.TAN_BED, new Item.Properties().stacksTo(1)));

    public static final Item MAROON_DYE_BASKET = register("maroon_dye_basket", new BlockItem(DDBlocks.MAROON_DYE_BASKET, new Item.Properties()));
    public static final Item ROSE_DYE_BASKET = register("rose_dye_basket", new BlockItem(DDBlocks.ROSE_DYE_BASKET, new Item.Properties()));
    public static final Item CORAL_DYE_BASKET = register("coral_dye_basket", new BlockItem(DDBlocks.CORAL_DYE_BASKET, new Item.Properties()));
    public static final Item INDIGO_DYE_BASKET = register("indigo_dye_basket", new BlockItem(DDBlocks.INDIGO_DYE_BASKET, new Item.Properties()));
    public static final Item NAVY_DYE_BASKET = register("navy_dye_basket", new BlockItem(DDBlocks.NAVY_DYE_BASKET, new Item.Properties()));
    public static final Item SLATE_DYE_BASKET = register("slate_dye_basket", new BlockItem(DDBlocks.SLATE_DYE_BASKET, new Item.Properties()));
    public static final Item OLIVE_DYE_BASKET = register("olive_dye_basket", new BlockItem(DDBlocks.OLIVE_DYE_BASKET, new Item.Properties()));
    public static final Item AMBER_DYE_BASKET = register("amber_dye_basket", new BlockItem(DDBlocks.AMBER_DYE_BASKET, new Item.Properties()));
    public static final Item BEIGE_DYE_BASKET = register("beige_dye_basket", new BlockItem(DDBlocks.BEIGE_DYE_BASKET, new Item.Properties()));
    public static final Item TEAL_DYE_BASKET = register("teal_dye_basket", new BlockItem(DDBlocks.TEAL_DYE_BASKET, new Item.Properties()));
    public static final Item MINT_DYE_BASKET = register("mint_dye_basket", new BlockItem(DDBlocks.MINT_DYE_BASKET, new Item.Properties()));
    public static final Item AQUA_DYE_BASKET = register("aqua_dye_basket", new BlockItem(DDBlocks.AQUA_DYE_BASKET, new Item.Properties()));
    public static final Item VERDANT_DYE_BASKET = register("verdant_dye_basket", new BlockItem(DDBlocks.VERDANT_DYE_BASKET, new Item.Properties()));
    public static final Item FOREST_DYE_BASKET = register("forest_dye_basket", new BlockItem(DDBlocks.FOREST_DYE_BASKET, new Item.Properties()));
    public static final Item GINGER_DYE_BASKET = register("ginger_dye_basket", new BlockItem(DDBlocks.GINGER_DYE_BASKET, new Item.Properties()));
    public static final Item TAN_DYE_BASKET = register("tan_dye_basket", new BlockItem(DDBlocks.TAN_DYE_BASKET, new Item.Properties()));
    public static final Item WHITE_DYE_BASKET = register("white_dye_basket", new BlockItem(DDBlocks.WHITE_DYE_BASKET, new Item.Properties()));
    public static final Item LIGHT_GRAY_DYE_BASKET = register("light_gray_dye_basket", new BlockItem(DDBlocks.LIGHT_GRAY_DYE_BASKET, new Item.Properties()));
    public static final Item GRAY_DYE_BASKET = register("gray_dye_basket", new BlockItem(DDBlocks.GRAY_DYE_BASKET, new Item.Properties()));
    public static final Item BLACK_DYE_BASKET = register("black_dye_basket", new BlockItem(DDBlocks.BLACK_DYE_BASKET, new Item.Properties()));
    public static final Item BROWN_DYE_BASKET = register("brown_dye_basket", new BlockItem(DDBlocks.BROWN_DYE_BASKET, new Item.Properties()));
    public static final Item RED_DYE_BASKET = register("red_dye_basket", new BlockItem(DDBlocks.RED_DYE_BASKET, new Item.Properties()));
    public static final Item ORANGE_DYE_BASKET = register("orange_dye_basket", new BlockItem(DDBlocks.ORANGE_DYE_BASKET, new Item.Properties()));
    public static final Item YELLOW_DYE_BASKET = register("yellow_dye_basket", new BlockItem(DDBlocks.YELLOW_DYE_BASKET, new Item.Properties()));
    public static final Item LIME_DYE_BASKET = register("lime_dye_basket", new BlockItem(DDBlocks.LIME_DYE_BASKET, new Item.Properties()));
    public static final Item CYAN_DYE_BASKET = register("cyan_dye_basket", new BlockItem(DDBlocks.CYAN_DYE_BASKET, new Item.Properties()));
    public static final Item GREEN_DYE_BASKET = register("green_dye_basket", new BlockItem(DDBlocks.GREEN_DYE_BASKET, new Item.Properties()));
    public static final Item BLUE_DYE_BASKET = register("blue_dye_basket", new BlockItem(DDBlocks.BLUE_DYE_BASKET, new Item.Properties()));
    public static final Item LIGHT_BLUE_DYE_BASKET = register("light_blue_dye_basket", new BlockItem(DDBlocks.LIGHT_BLUE_DYE_BASKET, new Item.Properties()));
    public static final Item PURPLE_DYE_BASKET = register("purple_dye_basket", new BlockItem(DDBlocks.PURPLE_DYE_BASKET, new Item.Properties()));
    public static final Item MAGENTA_DYE_BASKET = register("magenta_dye_basket", new BlockItem(DDBlocks.MAGENTA_DYE_BASKET, new Item.Properties()));
    public static final Item PINK_DYE_BASKET = register("pink_dye_basket", new BlockItem(DDBlocks.PINK_DYE_BASKET, new Item.Properties()));

    private static Item register(String id, Item item) {
        return Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(DyeDepot.MOD_ID, id), item);
    }
}
