package com.ninni.dye_depot.registry;

import com.ninni.dye_depot.DyeDepot;
import com.ninni.dye_depot.items.DDBedItem;
import com.ninni.dye_depot.items.DDShulkerBoxItem;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BannerItem;
import net.minecraft.world.item.BedItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.DyeItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

@Mod.EventBusSubscriber(modid = DyeDepot.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class DDItems {

    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, DyeDepot.MOD_ID);

    public static final RegistryObject<Item> MAROON_DYE = ITEMS.register("maroon_dye", () -> new DyeItem(DDDyeKeys.MAROON, new Item.Properties()));
    public static final RegistryObject<Item> ROSE_DYE = ITEMS.register("rose_dye", () -> new DyeItem(DDDyeKeys.ROSE, new Item.Properties()));
    public static final RegistryObject<Item> CORAL_DYE = ITEMS.register("coral_dye", () -> new DyeItem(DDDyeKeys.CORAL, new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_DYE = ITEMS.register("indigo_dye", () -> new DyeItem(DDDyeKeys.INDIGO, new Item.Properties()));
    public static final RegistryObject<Item> NAVY_DYE = ITEMS.register("navy_dye", () -> new DyeItem(DDDyeKeys.NAVY, new Item.Properties()));
    public static final RegistryObject<Item> SLATE_DYE = ITEMS.register("slate_dye", () -> new DyeItem(DDDyeKeys.SLATE, new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_DYE = ITEMS.register("olive_dye", () -> new DyeItem(DDDyeKeys.OLIVE, new Item.Properties()));
    public static final RegistryObject<Item> AMBER_DYE = ITEMS.register("amber_dye", () -> new DyeItem(DDDyeKeys.AMBER, new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_DYE = ITEMS.register("beige_dye", () -> new DyeItem(DDDyeKeys.BEIGE, new Item.Properties()));
    public static final RegistryObject<Item> TEAL_DYE = ITEMS.register("teal_dye", () -> new DyeItem(DDDyeKeys.TEAL, new Item.Properties()));
    public static final RegistryObject<Item> MINT_DYE = ITEMS.register("mint_dye", () -> new DyeItem(DDDyeKeys.MINT, new Item.Properties()));
    public static final RegistryObject<Item> AQUA_DYE = ITEMS.register("aqua_dye", () -> new DyeItem(DDDyeKeys.AQUA, new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_DYE = ITEMS.register("verdant_dye", () -> new DyeItem(DDDyeKeys.VERDANT, new Item.Properties()));
    public static final RegistryObject<Item> FOREST_DYE = ITEMS.register("forest_dye", () -> new DyeItem(DDDyeKeys.FOREST, new Item.Properties()));
    public static final RegistryObject<Item> GINGER_DYE = ITEMS.register("ginger_dye", () -> new DyeItem(DDDyeKeys.GINGER, new Item.Properties()));
    public static final RegistryObject<Item> TAN_DYE = ITEMS.register("tan_dye", () -> new DyeItem(DDDyeKeys.TAN, new Item.Properties()));

    public static final RegistryObject<Item> MAROON_WOOL = ITEMS.register("maroon_wool", () -> new BlockItem(DDBlocks.MAROON_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_WOOL = ITEMS.register("rose_wool", () -> new BlockItem(DDBlocks.ROSE_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_WOOL = ITEMS.register("coral_wool", () -> new BlockItem(DDBlocks.CORAL_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_WOOL = ITEMS.register("indigo_wool", () -> new BlockItem(DDBlocks.INDIGO_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_WOOL = ITEMS.register("navy_wool", () -> new BlockItem(DDBlocks.NAVY_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_WOOL = ITEMS.register("slate_wool", () -> new BlockItem(DDBlocks.SLATE_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_WOOL = ITEMS.register("olive_wool", () -> new BlockItem(DDBlocks.OLIVE_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_WOOL = ITEMS.register("amber_wool", () -> new BlockItem(DDBlocks.AMBER_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_WOOL = ITEMS.register("beige_wool", () -> new BlockItem(DDBlocks.BEIGE_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_WOOL = ITEMS.register("teal_wool", () -> new BlockItem(DDBlocks.TEAL_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_WOOL = ITEMS.register("mint_wool", () -> new BlockItem(DDBlocks.MINT_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_WOOL = ITEMS.register("aqua_wool", () -> new BlockItem(DDBlocks.AQUA_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_WOOL = ITEMS.register("verdant_wool", () -> new BlockItem(DDBlocks.VERDANT_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_WOOL = ITEMS.register("forest_wool", () -> new BlockItem(DDBlocks.FOREST_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_WOOL = ITEMS.register("ginger_wool", () -> new BlockItem(DDBlocks.GINGER_WOOL.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_WOOL = ITEMS.register("tan_wool", () -> new BlockItem(DDBlocks.TAN_WOOL.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_CARPET = ITEMS.register("maroon_carpet", () -> new BlockItem(DDBlocks.MAROON_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_CARPET = ITEMS.register("rose_carpet", () -> new BlockItem(DDBlocks.ROSE_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_CARPET = ITEMS.register("coral_carpet", () -> new BlockItem(DDBlocks.CORAL_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_CARPET = ITEMS.register("indigo_carpet", () -> new BlockItem(DDBlocks.INDIGO_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_CARPET = ITEMS.register("navy_carpet", () -> new BlockItem(DDBlocks.NAVY_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_CARPET = ITEMS.register("slate_carpet", () -> new BlockItem(DDBlocks.SLATE_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_CARPET = ITEMS.register("olive_carpet", () -> new BlockItem(DDBlocks.OLIVE_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_CARPET = ITEMS.register("amber_carpet", () -> new BlockItem(DDBlocks.AMBER_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_CARPET = ITEMS.register("beige_carpet", () -> new BlockItem(DDBlocks.BEIGE_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_CARPET = ITEMS.register("teal_carpet", () -> new BlockItem(DDBlocks.TEAL_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_CARPET = ITEMS.register("mint_carpet", () -> new BlockItem(DDBlocks.MINT_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_CARPET = ITEMS.register("aqua_carpet", () -> new BlockItem(DDBlocks.AQUA_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_CARPET = ITEMS.register("verdant_carpet", () -> new BlockItem(DDBlocks.VERDANT_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_CARPET = ITEMS.register("forest_carpet", () -> new BlockItem(DDBlocks.FOREST_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_CARPET = ITEMS.register("ginger_carpet", () -> new BlockItem(DDBlocks.GINGER_CARPET.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_CARPET = ITEMS.register("tan_carpet", () -> new BlockItem(DDBlocks.TAN_CARPET.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_TERRACOTTA = ITEMS.register("maroon_terracotta", () -> new BlockItem(DDBlocks.MAROON_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_TERRACOTTA = ITEMS.register("rose_terracotta", () -> new BlockItem(DDBlocks.ROSE_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_TERRACOTTA = ITEMS.register("coral_terracotta", () -> new BlockItem(DDBlocks.CORAL_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_TERRACOTTA = ITEMS.register("indigo_terracotta", () -> new BlockItem(DDBlocks.INDIGO_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_TERRACOTTA = ITEMS.register("navy_terracotta", () -> new BlockItem(DDBlocks.NAVY_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_TERRACOTTA = ITEMS.register("slate_terracotta", () -> new BlockItem(DDBlocks.SLATE_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_TERRACOTTA = ITEMS.register("olive_terracotta", () -> new BlockItem(DDBlocks.OLIVE_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_TERRACOTTA = ITEMS.register("amber_terracotta", () -> new BlockItem(DDBlocks.AMBER_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_TERRACOTTA = ITEMS.register("beige_terracotta", () -> new BlockItem(DDBlocks.BEIGE_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_TERRACOTTA = ITEMS.register("teal_terracotta", () -> new BlockItem(DDBlocks.TEAL_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_TERRACOTTA = ITEMS.register("mint_terracotta", () -> new BlockItem(DDBlocks.MINT_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_TERRACOTTA = ITEMS.register("aqua_terracotta", () -> new BlockItem(DDBlocks.AQUA_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_TERRACOTTA = ITEMS.register("verdant_terracotta", () -> new BlockItem(DDBlocks.VERDANT_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_TERRACOTTA = ITEMS.register("forest_terracotta", () -> new BlockItem(DDBlocks.FOREST_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_TERRACOTTA = ITEMS.register("ginger_terracotta", () -> new BlockItem(DDBlocks.GINGER_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_TERRACOTTA = ITEMS.register("tan_terracotta", () -> new BlockItem(DDBlocks.TAN_TERRACOTTA.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_CONCRETE = ITEMS.register("maroon_concrete", () -> new BlockItem(DDBlocks.MAROON_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_CONCRETE = ITEMS.register("rose_concrete", () -> new BlockItem(DDBlocks.ROSE_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_CONCRETE = ITEMS.register("coral_concrete", () -> new BlockItem(DDBlocks.CORAL_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_CONCRETE = ITEMS.register("indigo_concrete", () -> new BlockItem(DDBlocks.INDIGO_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_CONCRETE = ITEMS.register("navy_concrete", () -> new BlockItem(DDBlocks.NAVY_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_CONCRETE = ITEMS.register("slate_concrete", () -> new BlockItem(DDBlocks.SLATE_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_CONCRETE = ITEMS.register("olive_concrete", () -> new BlockItem(DDBlocks.OLIVE_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_CONCRETE = ITEMS.register("amber_concrete", () -> new BlockItem(DDBlocks.AMBER_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_CONCRETE = ITEMS.register("beige_concrete", () -> new BlockItem(DDBlocks.BEIGE_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_CONCRETE = ITEMS.register("teal_concrete", () -> new BlockItem(DDBlocks.TEAL_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_CONCRETE = ITEMS.register("mint_concrete", () -> new BlockItem(DDBlocks.MINT_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_CONCRETE = ITEMS.register("aqua_concrete", () -> new BlockItem(DDBlocks.AQUA_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_CONCRETE = ITEMS.register("verdant_concrete", () -> new BlockItem(DDBlocks.VERDANT_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_CONCRETE = ITEMS.register("forest_concrete", () -> new BlockItem(DDBlocks.FOREST_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_CONCRETE = ITEMS.register("ginger_concrete", () -> new BlockItem(DDBlocks.GINGER_CONCRETE.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_CONCRETE = ITEMS.register("tan_concrete", () -> new BlockItem(DDBlocks.TAN_CONCRETE.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_CONCRETE_POWDER = ITEMS.register("maroon_concrete_powder", () -> new BlockItem(DDBlocks.MAROON_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_CONCRETE_POWDER = ITEMS.register("rose_concrete_powder", () -> new BlockItem(DDBlocks.ROSE_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_CONCRETE_POWDER = ITEMS.register("coral_concrete_powder", () -> new BlockItem(DDBlocks.CORAL_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_CONCRETE_POWDER = ITEMS.register("indigo_concrete_powder", () -> new BlockItem(DDBlocks.INDIGO_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_CONCRETE_POWDER = ITEMS.register("navy_concrete_powder", () -> new BlockItem(DDBlocks.NAVY_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_CONCRETE_POWDER = ITEMS.register("slate_concrete_powder", () -> new BlockItem(DDBlocks.SLATE_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_CONCRETE_POWDER = ITEMS.register("olive_concrete_powder", () -> new BlockItem(DDBlocks.OLIVE_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_CONCRETE_POWDER = ITEMS.register("amber_concrete_powder", () -> new BlockItem(DDBlocks.AMBER_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_CONCRETE_POWDER = ITEMS.register("beige_concrete_powder", () -> new BlockItem(DDBlocks.BEIGE_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_CONCRETE_POWDER = ITEMS.register("teal_concrete_powder", () -> new BlockItem(DDBlocks.TEAL_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_CONCRETE_POWDER = ITEMS.register("mint_concrete_powder", () -> new BlockItem(DDBlocks.MINT_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_CONCRETE_POWDER = ITEMS.register("aqua_concrete_powder", () -> new BlockItem(DDBlocks.AQUA_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_CONCRETE_POWDER = ITEMS.register("verdant_concrete_powder", () -> new BlockItem(DDBlocks.VERDANT_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_CONCRETE_POWDER = ITEMS.register("forest_concrete_powder", () -> new BlockItem(DDBlocks.FOREST_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_CONCRETE_POWDER = ITEMS.register("ginger_concrete_powder", () -> new BlockItem(DDBlocks.GINGER_CONCRETE_POWDER.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_CONCRETE_POWDER = ITEMS.register("tan_concrete_powder", () -> new BlockItem(DDBlocks.TAN_CONCRETE_POWDER.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_GLAZED_TERRACOTTA = ITEMS.register("maroon_glazed_terracotta", () -> new BlockItem(DDBlocks.MAROON_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_GLAZED_TERRACOTTA = ITEMS.register("rose_glazed_terracotta", () -> new BlockItem(DDBlocks.ROSE_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_GLAZED_TERRACOTTA = ITEMS.register("coral_glazed_terracotta", () -> new BlockItem(DDBlocks.CORAL_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_GLAZED_TERRACOTTA = ITEMS.register("indigo_glazed_terracotta", () -> new BlockItem(DDBlocks.INDIGO_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_GLAZED_TERRACOTTA = ITEMS.register("navy_glazed_terracotta", () -> new BlockItem(DDBlocks.NAVY_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_GLAZED_TERRACOTTA = ITEMS.register("slate_glazed_terracotta", () -> new BlockItem(DDBlocks.SLATE_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_GLAZED_TERRACOTTA = ITEMS.register("olive_glazed_terracotta", () -> new BlockItem(DDBlocks.OLIVE_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_GLAZED_TERRACOTTA = ITEMS.register("amber_glazed_terracotta", () -> new BlockItem(DDBlocks.AMBER_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_GLAZED_TERRACOTTA = ITEMS.register("beige_glazed_terracotta", () -> new BlockItem(DDBlocks.BEIGE_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_GLAZED_TERRACOTTA = ITEMS.register("teal_glazed_terracotta", () -> new BlockItem(DDBlocks.TEAL_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_GLAZED_TERRACOTTA = ITEMS.register("mint_glazed_terracotta", () -> new BlockItem(DDBlocks.MINT_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_GLAZED_TERRACOTTA = ITEMS.register("aqua_glazed_terracotta", () -> new BlockItem(DDBlocks.AQUA_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_GLAZED_TERRACOTTA = ITEMS.register("verdant_glazed_terracotta", () -> new BlockItem(DDBlocks.VERDANT_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_GLAZED_TERRACOTTA = ITEMS.register("forest_glazed_terracotta", () -> new BlockItem(DDBlocks.FOREST_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_GLAZED_TERRACOTTA = ITEMS.register("ginger_glazed_terracotta", () -> new BlockItem(DDBlocks.GINGER_GLAZED_TERRACOTTA.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_GLAZED_TERRACOTTA = ITEMS.register("tan_glazed_terracotta", () -> new BlockItem(DDBlocks.TAN_GLAZED_TERRACOTTA.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_STAINED_GLASS = ITEMS.register("maroon_stained_glass", () -> new BlockItem(DDBlocks.MAROON_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_STAINED_GLASS = ITEMS.register("rose_stained_glass", () -> new BlockItem(DDBlocks.ROSE_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_STAINED_GLASS = ITEMS.register("coral_stained_glass", () -> new BlockItem(DDBlocks.CORAL_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_STAINED_GLASS = ITEMS.register("indigo_stained_glass", () -> new BlockItem(DDBlocks.INDIGO_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_STAINED_GLASS = ITEMS.register("navy_stained_glass", () -> new BlockItem(DDBlocks.NAVY_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_STAINED_GLASS = ITEMS.register("slate_stained_glass", () -> new BlockItem(DDBlocks.SLATE_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_STAINED_GLASS = ITEMS.register("olive_stained_glass", () -> new BlockItem(DDBlocks.OLIVE_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_STAINED_GLASS = ITEMS.register("amber_stained_glass", () -> new BlockItem(DDBlocks.AMBER_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_STAINED_GLASS = ITEMS.register("beige_stained_glass", () -> new BlockItem(DDBlocks.BEIGE_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_STAINED_GLASS = ITEMS.register("teal_stained_glass", () -> new BlockItem(DDBlocks.TEAL_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_STAINED_GLASS = ITEMS.register("mint_stained_glass", () -> new BlockItem(DDBlocks.MINT_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_STAINED_GLASS = ITEMS.register("aqua_stained_glass", () -> new BlockItem(DDBlocks.AQUA_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_STAINED_GLASS = ITEMS.register("verdant_stained_glass", () -> new BlockItem(DDBlocks.VERDANT_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_STAINED_GLASS = ITEMS.register("forest_stained_glass", () -> new BlockItem(DDBlocks.FOREST_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_STAINED_GLASS = ITEMS.register("ginger_stained_glass", () -> new BlockItem(DDBlocks.GINGER_STAINED_GLASS.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_STAINED_GLASS = ITEMS.register("tan_stained_glass", () -> new BlockItem(DDBlocks.TAN_STAINED_GLASS.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_STAINED_GLASS_PANE = ITEMS.register("maroon_stained_glass_pane", () -> new BlockItem(DDBlocks.MAROON_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_STAINED_GLASS_PANE = ITEMS.register("rose_stained_glass_pane", () -> new BlockItem(DDBlocks.ROSE_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_STAINED_GLASS_PANE = ITEMS.register("coral_stained_glass_pane", () -> new BlockItem(DDBlocks.CORAL_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_STAINED_GLASS_PANE = ITEMS.register("indigo_stained_glass_pane", () -> new BlockItem(DDBlocks.INDIGO_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_STAINED_GLASS_PANE = ITEMS.register("navy_stained_glass_pane", () -> new BlockItem(DDBlocks.NAVY_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_STAINED_GLASS_PANE = ITEMS.register("slate_stained_glass_pane", () -> new BlockItem(DDBlocks.SLATE_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_STAINED_GLASS_PANE = ITEMS.register("olive_stained_glass_pane", () -> new BlockItem(DDBlocks.OLIVE_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_STAINED_GLASS_PANE = ITEMS.register("amber_stained_glass_pane", () -> new BlockItem(DDBlocks.AMBER_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_STAINED_GLASS_PANE = ITEMS.register("beige_stained_glass_pane", () -> new BlockItem(DDBlocks.BEIGE_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_STAINED_GLASS_PANE = ITEMS.register("teal_stained_glass_pane", () -> new BlockItem(DDBlocks.TEAL_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_STAINED_GLASS_PANE = ITEMS.register("mint_stained_glass_pane", () -> new BlockItem(DDBlocks.MINT_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_STAINED_GLASS_PANE = ITEMS.register("aqua_stained_glass_pane", () -> new BlockItem(DDBlocks.AQUA_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_STAINED_GLASS_PANE = ITEMS.register("verdant_stained_glass_pane", () -> new BlockItem(DDBlocks.VERDANT_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_STAINED_GLASS_PANE = ITEMS.register("forest_stained_glass_pane", () -> new BlockItem(DDBlocks.FOREST_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_STAINED_GLASS_PANE = ITEMS.register("ginger_stained_glass_pane", () -> new BlockItem(DDBlocks.GINGER_STAINED_GLASS_PANE.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_STAINED_GLASS_PANE = ITEMS.register("tan_stained_glass_pane", () -> new BlockItem(DDBlocks.TAN_STAINED_GLASS_PANE.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_SHULKER_BOX = ITEMS.register("maroon_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.MAROON_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> ROSE_SHULKER_BOX = ITEMS.register("rose_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.ROSE_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> CORAL_SHULKER_BOX = ITEMS.register("coral_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.CORAL_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> INDIGO_SHULKER_BOX = ITEMS.register("indigo_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.INDIGO_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> NAVY_SHULKER_BOX = ITEMS.register("navy_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.NAVY_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> SLATE_SHULKER_BOX = ITEMS.register("slate_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.SLATE_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> OLIVE_SHULKER_BOX = ITEMS.register("olive_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.OLIVE_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> AMBER_SHULKER_BOX = ITEMS.register("amber_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.AMBER_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> BEIGE_SHULKER_BOX = ITEMS.register("beige_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.BEIGE_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> TEAL_SHULKER_BOX = ITEMS.register("teal_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.TEAL_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> MINT_SHULKER_BOX = ITEMS.register("mint_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.MINT_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> AQUA_SHULKER_BOX = ITEMS.register("aqua_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.AQUA_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> VERDANT_SHULKER_BOX = ITEMS.register("verdant_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.VERDANT_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> FOREST_SHULKER_BOX = ITEMS.register("forest_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.FOREST_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> GINGER_SHULKER_BOX = ITEMS.register("ginger_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.GINGER_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> TAN_SHULKER_BOX = ITEMS.register("tan_shulker_box", () -> new DDShulkerBoxItem(DDBlocks.TAN_SHULKER_BOX.get(), new Item.Properties().stacksTo(1)));

    public static final RegistryObject<Item> MAROON_CANDLE = ITEMS.register("maroon_candle", () -> new BlockItem(DDBlocks.MAROON_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_CANDLE = ITEMS.register("rose_candle", () -> new BlockItem(DDBlocks.ROSE_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_CANDLE = ITEMS.register("coral_candle", () -> new BlockItem(DDBlocks.CORAL_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_CANDLE = ITEMS.register("indigo_candle", () -> new BlockItem(DDBlocks.INDIGO_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_CANDLE = ITEMS.register("navy_candle", () -> new BlockItem(DDBlocks.NAVY_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_CANDLE = ITEMS.register("slate_candle", () -> new BlockItem(DDBlocks.SLATE_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_CANDLE = ITEMS.register("olive_candle", () -> new BlockItem(DDBlocks.OLIVE_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_CANDLE = ITEMS.register("amber_candle", () -> new BlockItem(DDBlocks.AMBER_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_CANDLE = ITEMS.register("beige_candle", () -> new BlockItem(DDBlocks.BEIGE_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_CANDLE = ITEMS.register("teal_candle", () -> new BlockItem(DDBlocks.TEAL_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_CANDLE = ITEMS.register("mint_candle", () -> new BlockItem(DDBlocks.MINT_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_CANDLE = ITEMS.register("aqua_candle", () -> new BlockItem(DDBlocks.AQUA_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_CANDLE = ITEMS.register("verdant_candle", () -> new BlockItem(DDBlocks.VERDANT_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_CANDLE = ITEMS.register("forest_candle", () -> new BlockItem(DDBlocks.FOREST_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_CANDLE = ITEMS.register("ginger_candle", () -> new BlockItem(DDBlocks.GINGER_CANDLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_CANDLE = ITEMS.register("tan_candle", () -> new BlockItem(DDBlocks.TAN_CANDLE.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_BANNER = ITEMS.register("maroon_banner", () -> new BannerItem(DDBlocks.MAROON_BANNER.get(),DDBlocks.MAROON_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> ROSE_BANNER = ITEMS.register("rose_banner", () -> new BannerItem(DDBlocks.ROSE_BANNER.get(),DDBlocks.ROSE_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> CORAL_BANNER = ITEMS.register("coral_banner", () -> new BannerItem(DDBlocks.CORAL_BANNER.get(),DDBlocks.CORAL_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> INDIGO_BANNER = ITEMS.register("indigo_banner", () -> new BannerItem(DDBlocks.INDIGO_BANNER.get(),DDBlocks.INDIGO_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> NAVY_BANNER = ITEMS.register("navy_banner", () -> new BannerItem(DDBlocks.NAVY_BANNER.get(),DDBlocks.NAVY_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> SLATE_BANNER = ITEMS.register("slate_banner", () -> new BannerItem(DDBlocks.SLATE_BANNER.get(),DDBlocks.SLATE_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> OLIVE_BANNER = ITEMS.register("olive_banner", () -> new BannerItem(DDBlocks.OLIVE_BANNER.get(),DDBlocks.OLIVE_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> AMBER_BANNER = ITEMS.register("amber_banner", () -> new BannerItem(DDBlocks.AMBER_BANNER.get(),DDBlocks.AMBER_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> BEIGE_BANNER = ITEMS.register("beige_banner", () -> new BannerItem(DDBlocks.BEIGE_BANNER.get(),DDBlocks.BEIGE_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> TEAL_BANNER = ITEMS.register("teal_banner", () -> new BannerItem(DDBlocks.TEAL_BANNER.get(),DDBlocks.TEAL_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> MINT_BANNER = ITEMS.register("mint_banner", () -> new BannerItem(DDBlocks.MINT_BANNER.get(),DDBlocks.MINT_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> AQUA_BANNER = ITEMS.register("aqua_banner", () -> new BannerItem(DDBlocks.AQUA_BANNER.get(),DDBlocks.AQUA_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> VERDANT_BANNER = ITEMS.register("verdant_banner", () -> new BannerItem(DDBlocks.VERDANT_BANNER.get(),DDBlocks.VERDANT_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> FOREST_BANNER = ITEMS.register("forest_banner", () -> new BannerItem(DDBlocks.FOREST_BANNER.get(),DDBlocks.FOREST_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> GINGER_BANNER = ITEMS.register("ginger_banner", () -> new BannerItem(DDBlocks.GINGER_BANNER.get(),DDBlocks.GINGER_WALL_BANNER.get(), new Item.Properties()));
    public static final RegistryObject<Item> TAN_BANNER = ITEMS.register("tan_banner", () -> new BannerItem(DDBlocks.TAN_BANNER.get(),DDBlocks.TAN_WALL_BANNER.get(), new Item.Properties()));

    public static final RegistryObject<Item> MAROON_BED = ITEMS.register("maroon_bed", () -> new DDBedItem(DDBlocks.MAROON_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> ROSE_BED = ITEMS.register("rose_bed", () -> new DDBedItem(DDBlocks.ROSE_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> CORAL_BED = ITEMS.register("coral_bed", () -> new DDBedItem(DDBlocks.CORAL_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> INDIGO_BED = ITEMS.register("indigo_bed", () -> new DDBedItem(DDBlocks.INDIGO_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> NAVY_BED = ITEMS.register("navy_bed", () -> new DDBedItem(DDBlocks.NAVY_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> SLATE_BED = ITEMS.register("slate_bed", () -> new DDBedItem(DDBlocks.SLATE_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> OLIVE_BED = ITEMS.register("olive_bed", () -> new DDBedItem(DDBlocks.OLIVE_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> AMBER_BED = ITEMS.register("amber_bed", () -> new DDBedItem(DDBlocks.AMBER_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> BEIGE_BED = ITEMS.register("beige_bed", () -> new DDBedItem(DDBlocks.BEIGE_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> TEAL_BED = ITEMS.register("teal_bed", () -> new DDBedItem(DDBlocks.TEAL_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> MINT_BED = ITEMS.register("mint_bed", () -> new DDBedItem(DDBlocks.MINT_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> AQUA_BED = ITEMS.register("aqua_bed", () -> new DDBedItem(DDBlocks.AQUA_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> VERDANT_BED = ITEMS.register("verdant_bed", () -> new DDBedItem(DDBlocks.VERDANT_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> FOREST_BED = ITEMS.register("forest_bed", () -> new DDBedItem(DDBlocks.FOREST_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> GINGER_BED = ITEMS.register("ginger_bed", () -> new DDBedItem(DDBlocks.GINGER_BED.get(), new Item.Properties().stacksTo(1)));
    public static final RegistryObject<Item> TAN_BED = ITEMS.register("tan_bed", () -> new DDBedItem(DDBlocks.TAN_BED.get(), new Item.Properties().stacksTo(1)));

    private static Item register(String id, Item item) {
        return Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(DyeDepot.MOD_ID, id), item);
    }
}
